### ISSUE TITLE
Landrop on android crashed when send a .jpg file to another android device.

### ISSUE THREAD

**Issue by CharaDust** [LANDrop/LANDrop#220]
将 .jpg 文件发送到另一个 Android 设备时，Android 上的 Landdrop 崩溃了
Landrop on android crashed when send a .jpg file to another android device.

这里是崩溃日志的链接与文本
Here are the crash log link and text.
[https://paste.crdroid.net/3L3ptY](https://paste.crdroid.net/3L3ptY)
```
time: 1732028004349
msg: java.lang.IllegalStateException: Reply already submitted
stacktrace: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=4, result=-1, data=null} to activity {app.landrop.landrop_flutter/app.landrop.landrop_flutter.MainActivity}: java.lang.IllegalStateException: Reply already submitted
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5354)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5393)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7939)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
Caused by: java.lang.IllegalStateException: Reply already submitted
	at q4.c$g.a(Unknown Source:35)
	at c5.k$a$a.success(Unknown Source:14)
	at l4.n.x(Unknown Source:44)
	at l4.n.onMethodCall(Unknown Source:228)
	at l4.n.p(Unknown Source:82)
	at l4.n.h(Unknown Source:0)
	at l4.e.a(Unknown Source:2)
	at io.flutter.embedding.engine.c$c.h(Unknown Source:25)
	at io.flutter.embedding.engine.c.a(Unknown Source:14)
	at io.flutter.embedding.android.e.r(Unknown Source:51)
	at io.flutter.embedding.android.d.onActivityResult(Unknown Source:10)
	at android.app.Activity.dispatchActivityResult(Activity.java:8683)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5347)
	... 13 more
```

**Comment by KARkitkat** [comment]
Here is a similar case

https://github.com/user-attachments/assets/f02ad44e-0817-421a-8911-8da05c338d4e

```
time: 1732028506104
msg: java.lang.IllegalStateException: Reply already submitted
stacktrace: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=4, result=-1, data=null} to activity {app.landrop.landrop_flutter/app.landrop.landrop_flutter.MainActivity}: java.lang.IllegalStateException: Reply already submitted
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5354)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5393)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7939)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
Caused by: java.lang.IllegalStateException: Reply already submitted
	at q4.c$g.a(Unknown Source:35)
	at c5.k$a$a.success(Unknown Source:14)
	at l4.n.x(Unknown Source:44)
	at l4.n.onMethodCall(Unknown Source:228)
	at l4.n.p(Unknown Source:82)
	at l4.n.h(Unknown Source:0)
	at l4.e.a(Unknown Source:2)
	at io.flutter.embedding.engine.c$c.h(Unknown Source:25)
	at io.flutter.embedding.engine.c.a(Unknown Source:14)
	at io.flutter.embedding.android.e.r(Unknown Source:51)
	at io.flutter.embedding.android.d.onActivityResult(Unknown Source:10)
	at android.app.Activity.dispatchActivityResult(Activity.java:8683)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5347)
	... 13 more

```
